server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/change-log/db.change-log.sql

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auth-service-group
      auto-offset-reset: earliest

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  info:
    title: Auth Service API
    version: 1.0.0
    description: API для управления аутентификацией и авторизацией пользователей


jwt:
  secret: MySuperLongSecretKeyThatIsAtLeast32CharactersLong!
  expiration: 7200000

profile:
  service:
    url: http://profile-service:8082

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

