version: '3.8'

services:
  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - vet-network
    restart: unless-stopped

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_INTERNAL://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_INTERNAL://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - vet-network
    restart: unless-stopped

  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vet-network
    restart: unless-stopped

  # PostgreSQL
  postgresql:
    container_name: postgresql
    image: postgres:14
    environment:
      POSTGRES_USER: security_db
      POSTGRES_PASSWORD: example
      POSTGRES_DB: security_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vet-network
    restart: unless-stopped

  postgresql-appointment:
    image: postgres:14
    container_name: postgresql-appointment
    environment:
      POSTGRES_USER: appointment_user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: appointment_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_appointment_data:/var/lib/postgresql/data
      - ./appointment-service/db/migrations:/docker-entrypoint-initdb.d
    networks:
      - vet-network
    restart: unless-stopped

  # Сервис аутентификации
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    command: ["java", "-jar", "/app/auth.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: MySuperLongSecretKeyThatIsAtLeast32CharactersLong!
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/security_db
      SPRING_DATASOURCE_USERNAME: security_db
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"
    networks:
      - vet-network
    depends_on:
      - mongodb
      - postgresql
      - kafka
    restart: unless-stopped

  # Сервис профилей
  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profile-service
    command: ["java", "-jar", "/app/profile.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/profile_db?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8082:8082"
    networks:
      - vet-network
    depends_on:
      - mongodb
      - auth-service
      - kafka
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vet-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  # Сервис назначений
  appointment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment-service
    command: [ "java", "-jar", "/app/appointment.jar", "--spring.profiles.active=docker" ]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8083:8083"
    networks:
      - vet-network
    depends_on:
      - postgresql-appointment
      - redis
      - profile-service
      - auth-service
      - kafka
    restart: unless-stopped

  # Платежный сервис
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    command: ["java", "-jar", "/app/payment.jar", "--spring.profiles.active=docker"]
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8084:8084"
    networks:
      - vet-network
    depends_on:
      - auth-service
      - kafka
    restart: unless-stopped

volumes:
  mongodb_data:
  postgres_data:
  redis_data:
  postgres_appointment_data:

networks:
  vet-network:
    driver: bridge
    name: vet-network
    attachable: true
    external: false