version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vet-network
    restart: unless-stopped

  # PostgreSQL
  postgresql:
    container_name: postgresql  # Изменил имя для консистентности
    image: postgres:14
    environment:
      POSTGRES_USER: security_db
      POSTGRES_PASSWORD: example
      POSTGRES_DB: security_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vet-network
    restart: unless-stopped

  postgresql-appointment:
    image: postgres:14
    container_name: postgresql-appointment
    environment:
      POSTGRES_USER: appointment_user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: appointment_db
    ports:
      - "5433:5432"  # Маппинг на другой хост-порт
    volumes:
      - postgres_appointment_data:/var/lib/postgresql/data
      - ./appointment-service/db/migrations:/docker-entrypoint-initdb.d  # Для миграций
    networks:
      - vet-network
    restart: unless-stopped

  # Сервис аутентификации
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    command: ["java", "-jar", "/app/auth.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: MySuperLongSecretKeyThatIsAtLeast32CharactersLong!
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/security_db
      SPRING_DATASOURCE_USERNAME: security_db
      SPRING_DATASOURCE_PASSWORD: example
    ports:
      - "8081:8081"
    networks:
      - vet-network
    depends_on:
      - mongodb
      - postgresql
    restart: unless-stopped

  # Сервис профилей
  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profile-service
    command: ["java", "-jar", "/app/profile.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/profile_db?authSource=admin
    ports:
      - "8082:8082"
    networks:
      - vet-network
    depends_on:
      - mongodb
      - auth-service
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vet-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: unless-stopped

    # Обновлённый appointment-service
  appointment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment-service
    command: [ "java", "-jar", "/app/appointment.jar", "--spring.profiles.active=docker" ]
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"
    networks:
      - vet-network
    depends_on:
      - postgresql-appointment
      - redis
      - profile-service
      - auth-service
    restart: unless-stopped

  # Платежный сервис
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    command: ["java", "-jar", "/app/payment.jar", "--spring.profiles.active=docker"]
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    ports:
      - "8084:8084"
    networks:
      - vet-network
    depends_on:
      - auth-service
    restart: unless-stopped

volumes:
  mongodb_data:
  postgres_data:
  redis_data:
  postgres_appointment_data:

networks:
  vet-network:
    driver: bridge
    name: vet-network
    external: false



