server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/profile_db

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  info:
    title: PetClinic Profile Service API
    version: 1.0.0
    description: API для управления профилями, клиниками и питомцами

auth:
  service:
    url: http://auth-service:8081

appointment:
  service:
    url: http://appointment-service:8083

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic