--liquibase formatted sql

-- changeset yourname:001_create_tables

create table if not exists appointment (
    id          bigint              primary key generated by default as identity,
    clinic_id   varchar(256)        not null,
    vet_id      varchar(256)        not null,
    pet_id      varchar(256)        not null,
    start_time  timestamp           not null,
    end_time    timestamp           not null,
    status      varchar(20)         not null,
    notes       text
);

-- rollback drop table if exists appointment;
