spring:
  datasource:
    url: jdbc:postgresql://postgresql-appointment:5432/appointment_db
    username: appointment_user
    password: example
    driver-class-name: org.postgresql.Driver

  redis:
    host: redis
    port: 6379
    timeout: 5000
    database: 0
    cache:
      type: redis
      redis:
        time-to-live: 3600000

app:
  redis:
    timeout: 3600

laboratory:
  service:
    url: http://lab-service:8085