spring:
  datasource:
    url: jdbc:postgresql://postgresql-appointment:5432/appointment_db
    username: appointment_user
    password: example
    driver-class-name: org.postgresql.Driver
  redis:
    host: redis