server:
  port: 8083

app:
  redis:
    timeout: 3600 # 1 hour cache

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/change-log/db.change-log.sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  spring:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      database: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  info:
    title: PetClinic Appointment Service API
    version: 1.0.0
    description: API для управления записями к ветеринарам и генераии отчётов по анализам

profile:
  service:
    url: http://profile-service:8082

auth:
  service:
    url: http://auth-service:8081

laboratory:
  service:
    url: http://lab-service:8085

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic