server:
  port: 8083

app:
  redis:
    timeout: 3600 # 1 hour cache

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/change-log/db.change-log.sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  redis:
    host: redis
    port: 6379
    timeout: 5000
    database: 0
    cache:
      type: redis
      redis:
        time-to-live: 3600000



profile:
  service:
    url: http://profile-service:8082

auth:
  service:
    url: http://auth-service:8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic